#############################################################################
# Makefile for building: Mark
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  APP.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile APP.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
CFLAGS        = -pipe -g -D_REENTRANT -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=c++1y -D_REENTRANT -Wall -W -fPIC $(DEFINES)
LINK          = g++

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		pointer.cpp 
OBJECTS       = main.o \
		pointer.o

QMAKE_TARGET  = Mark
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = Mark


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)


all: Makefile $(TARGET)


####### Compile

main.o: main.cpp \
		pointer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

pointer.o: pointer.cpp pointer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pointer.o pointer.cpp


